services:
  # 1. Node.js (Express) Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: linkshrink_backend
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - linkshrink-network
    depends_on:
      - db
    environment:
      MONGO_HOST: ${NODE_MONGO_HOST}
      MONGO_PORT: ${NODE_MONGO_PORT}
      MONGO_DB_NAME: ${NODE_MONGO_DB_NAME}
      PORT: ${NODE_PORT}
      MONGO_USER: ${MONGO_ROOT_USER}
      MONGO_PASS: ${MONGO_ROOT_PASSWORD}

  # 2. Vue.js (Vite) Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: linkshrink_frontend
    ports:
      - "${VUE_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - linkshrink-network
    stdin_open: true
    tty: true

  # 3. MongoDB Database
  db:
    image: mongo:latest
    container_name: linkshrink_db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - linkshrink-network

networks:
  linkshrink-network:
    driver: bridge

volumes:
  mongo_data: